import { useState } from 'react';
import { api } from '../api/client';
import type { AskResponse } from '../api/types';
import { EmptyState } from '../components/EmptyState';
import { EntityBadge } from '../components/EntityBadge';
import { ErrorState } from '../components/ErrorState';
import { LoadingState } from '../components/LoadingState';

const examples = [
  'What should I check before changing Payment Validation Service?',
  'What happens when a pacs.008 payment fails sanctions screening?',
  'Which services are involved in outbound SWIFT pacs.008?',
  'What should a new support engineer learn first?',
];

export function AskPage() {
  const [question, setQuestion] = useState(examples[0]);
  const [mode, setMode] = useState<'deterministic' | 'ai_assisted'>('deterministic');
  const [answer, setAnswer] = useState<AskResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<unknown>(null);

  const submit = () => {
    setLoading(true);
    setError(null);
    api.ask({ question, mode }).then(setAnswer).catch(setError).finally(() => setLoading(false));
  };

  return (
    <section className="page-stack">
      <header className="page-header">
        <p className="eyebrow">Ask the Platform</p>
        <h2>Rule-based platform answers</h2>
        <p>Ask questions that can be answered from structured synthetic services, flows, runbooks, incidents, changes, tests, and glossary data.</p>
      </header>

      <section className="content-card">
        <label>
          Question
          <textarea value={question} onChange={(event) => setQuestion(event.target.value)} rows={4} />
        </label>
        <div className="example-row">
          {examples.map((item) => (
            <button key={item} onClick={() => setQuestion(item)}>{item}</button>
          ))}
        </div>

        <fieldset className="mode-selector">
          <legend>Answer mode</legend>
          <label className="radio-label">
            <input
              type="radio"
              name="mode"
              value="deterministic"
              checked={mode === 'deterministic'}
              onChange={() => setMode('deterministic')}
              disabled={loading}
            />
            Deterministic
            <span className="mode-description">Rule-based answer from structured synthetic data</span>
          </label>
          <label className="radio-label">
            <input
              type="radio"
              name="mode"
              value="ai_assisted"
              checked={mode === 'ai_assisted'}
              onChange={() => setMode('ai_assisted')}
              disabled={loading}
            />
            AI-assisted
            <span className="mode-description">Gemini explanation grounded in synthetic knowledge base</span>
          </label>
        </fieldset>

        <div className="safety-note">
          <p><strong>Note:</strong> AI-assisted answers are generated only from the synthetic Payments Platform Navigator knowledge base. They do not represent any real bank, real payment system, customer data, or production architecture.</p>
        </div>

        <button className="primary-action" onClick={submit} disabled={loading || question.trim().length < 3}>
          Ask
        </button>
      </section>

      {loading && <LoadingState label="Generating structured answer..." />}
      {error != null && <ErrorState error={error} />}
      {!loading && !error && !answer && <EmptyState title="No answer yet" message="Choose an example question or ask about a service, flow, runbook, or change." />}
      {answer && (
        <>
          {answer.ai_status?.available === false && (
            <section className="content-card warning-card">
              <p><strong>AI-assisted mode not available:</strong> {answer.ai_status.reason || 'AI explanations are not configured for this deployment.'}</p>
              <p>Showing deterministic answer from structured platform data.</p>
            </section>
          )}

          {answer.ai_explanation && answer.ai_status?.available !== false && (
            <section className="content-card ai-answer-card">
              <div className="card-heading-row">
                <h3>AI-assisted explanation</h3>
                {answer.ai_confidence !== undefined && (
                  <EntityBadge label={`confidence ${Math.round(answer.ai_confidence * 100)}%`} tone={answer.ai_confidence > 0.6 ? 'green' : 'amber'} />
                )}
              </div>
              <p className="answer-summary">{answer.ai_explanation}</p>
              {answer.ai_status?.guardrail_notes && (
                <div className="guardrail-note">
                  <p><strong>Guardrails:</strong> {answer.ai_status.guardrail_notes}</p>
                </div>
              )}
              {answer.ai_status?.provider && (
                <p className="subtle">Generated by {answer.ai_status.provider}</p>
              )}
            </section>
          )}

          <section className="content-card answer-card">
            <div className="card-heading-row">
              <h3>Deterministic answer</h3>
              <EntityBadge label={`confidence ${Math.round((answer.confidence || 0) * 100)}%`} tone={(answer.confidence || 0) > 0.6 ? 'green' : 'amber'} />
            </div>
            <p className="answer-summary">{answer.answer_summary}</p>
            <AnswerList title="Matched entities" items={Object.entries(answer.matched_entities || {}).flatMap(([key, values]) => values.map((value) => `${key}: ${value}`))} />
            <AnswerList title="Relevant services" items={answer.relevant_services} />
            <AnswerList title="Relevant flows" items={answer.relevant_flows} />
            <AnswerList title="Relevant runbooks" items={answer.relevant_runbooks} />
            <AnswerList title="Risks" items={(answer.relevant_risks || []).map((risk) => `${risk.id}: ${risk.title}`)} />
            <AnswerList title="Next steps" items={answer.suggested_next_steps} />
            <AnswerList title="Source files" items={answer.source_files} />
          </section>
        </>
      )}
    </section>
  );
}

function AnswerList({ title, items = [] }: { title: string; items?: string[] }) {
  return (
    <div className="answer-section">
      <h4>{title}</h4>
      {items.length === 0 ? <span className="subtle">No linked evidence returned.</span> : (
        <div className="chip-row">
          {items.map((item) => <span className="chip" key={item}>{item}</span>)}
        </div>
      )}
    </div>
  );
}
